/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.muni.fi.gui;

import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author V. Mecko
 *
 * to make it run you need jcalendar-1.4 plugin.
 */
public class AppForm extends javax.swing.JFrame {
     private static final ResourceBundle texts = ResourceBundle.getBundle("texts");
    
    private GuestTableModel guestTable;
    private RoomsTableModel roomTable;
    private ReservationTableModel reservationTable;
    
    /**
     * Creates new form AppForm
     */
    public AppForm() {
        initComponents();
        
        guestTable = (GuestTableModel) jTableGuest.getModel();
        roomTable = (RoomsTableModel) jTableRoom.getModel();
        reservationTable = (ReservationTableModel) jTableReservation.getModel();
    }

     private void showGuestFrame() {
        GuestFrame guestFrame = new GuestFrame(guestTable);
        guestFrame.setVisible(true);
    }
    
    private void showRoomFrame() {
        RoomFrame roomFrame = new RoomFrame(roomTable);
        roomFrame.setVisible(true);
    }
    
    private void showEmptyRoomsOptionFrame(){
        EmptyRoomsOptionFrame roomFrame = new EmptyRoomsOptionFrame();
        roomFrame.setVisible(true);
    }
    
    private void actionDeleteGuest() {
        int row = jTableGuest.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, texts.getString("notSelectGuest"), texts.getString("cantDeleteGuest"), JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (JOptionPane.showConfirmDialog(this, texts.getString("reallyDeleteGuest"), texts.getString("DeleteGuestBtn"), JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            guestTable.removeRow(row);
        }
    }
    
    private void actionDeleteRoom() {
        int row = jTableRoom.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, texts.getString("notSelectRoom"), texts.getString("cantDeleteRoom"), JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (JOptionPane.showConfirmDialog(this, texts.getString("reallyDeleteRoom"), texts.getString("DeleteRoomBtn"), JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            roomTable.removeRow(row);
        }
    }
    
    private void showReservationFrame(){
        ReservationFrame resFrame = new ReservationFrame(reservationTable);
        resFrame.setVisible(true);
    }
    
    private void actionCheckOut(){
        int row = jTableReservation.getSelectedRow();
        if(row < 0){
            JOptionPane.showMessageDialog(this, texts.getString("notSelectRes"),texts.getString("cantCheckout"),JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(JOptionPane.showConfirmDialog(this,texts.getString("reallyDeleteRes"),texts.getString("DeleteReservationBtn"),JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            reservationTable.removeRow(row);
        }
    }
    
    private void showFindGuestFrame(){
        int row = jTableGuest.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, texts.getString("notSelectGuest"), texts.getString("notSelectGuest"), JOptionPane.WARNING_MESSAGE);
            return;
        }
        FindGuestFrame findGuestFrame = new FindGuestFrame(new FindGuestTableModel(guestTable.getRow(row)));
        findGuestFrame.setVisible(true);
    }
    
    private void showFindRoomFrame(){
        int row = jTableRoom.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, texts.getString("notSelectRoom"), texts.getString("notSelectRoom"), JOptionPane.WARNING_MESSAGE);
            return;
        }
        FindRoomFrame findRoomFrame = new FindRoomFrame(new FindRoomTableModel(roomTable.getRow(row)));
        findRoomFrame.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPaneReservation = new javax.swing.JScrollPane();
        jTableReservation = new javax.swing.JTable();
        jPaneGuest = new javax.swing.JScrollPane();
        jTableGuest = new javax.swing.JTable();
        jPaneRoom = new javax.swing.JScrollPane();
        jTableRoom = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jBtnAddRes = new javax.swing.JButton();
        jBtnDeleteRes = new javax.swing.JButton();
        jBtnAddRoom = new javax.swing.JButton();
        jBtnDeleteRoom = new javax.swing.JButton();
        jBtnAddGuest = new javax.swing.JButton();
        jBtnDeleteGuest = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        jSeparator19 = new javax.swing.JToolBar.Separator();
        jBtnFindEmptyRoom = new javax.swing.JButton();
        JBtnFindGuest = new javax.swing.JButton();
        jBtnFindRoom = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemAbout = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane2StateChanged(evt);
            }
        });

        jTableReservation.setModel(new ReservationTableModel());
        jTableReservation.getColumnModel().getColumn(0).setMinWidth(0);
        jTableReservation.getColumnModel().getColumn(0).setMaxWidth(0);
        jTableReservation.getColumnModel().getColumn(0).setWidth(0);
        jPaneReservation.setViewportView(jTableReservation);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("texts"); // NOI18N
        jTabbedPane2.addTab(bundle.getString("Reservations"), jPaneReservation); // NOI18N

        jTableGuest.setModel(new GuestTableModel());
        jTableGuest.getColumnModel().getColumn(0).setMinWidth(0);
        jTableGuest.getColumnModel().getColumn(0).setMaxWidth(0);
        jTableGuest.getColumnModel().getColumn(0).setWidth(0);
        jTableGuest.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTableGuestFocusGained(evt);
            }
        });
        jPaneGuest.setViewportView(jTableGuest);

        jTabbedPane2.addTab(bundle.getString("Guests"), jPaneGuest); // NOI18N

        jTableRoom.setModel(new RoomsTableModel());
        jTableRoom.getColumnModel().getColumn(0).setMinWidth(0);
        jTableRoom.getColumnModel().getColumn(0).setMaxWidth(0);
        jTableRoom.getColumnModel().getColumn(0).setWidth(0);
        jTableRoom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTableRoomFocusGained(evt);
            }
        });
        jPaneRoom.setViewportView(jTableRoom);

        jTabbedPane2.addTab(bundle.getString("Rooms"), jPaneRoom); // NOI18N

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator2);

        jBtnAddRes.setText(bundle.getString("AddReservationBtn")); // NOI18N
        jBtnAddRes.setFocusable(false);
        jBtnAddRes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnAddRes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnAddRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddResActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnAddRes);
        jBtnAddRes.getAccessibleContext().setAccessibleName("jBtnAddRes");

        jBtnDeleteRes.setText(bundle.getString("DeleteReservationBtn")); // NOI18N
        jBtnDeleteRes.setFocusable(false);
        jBtnDeleteRes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnDeleteRes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnDeleteRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeleteResActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnDeleteRes);
        jBtnDeleteRes.getAccessibleContext().setAccessibleName("jBtnDeleteRes");

        jBtnAddRoom.setText(bundle.getString("AddRoomBtn")); // NOI18N
        jBtnAddRoom.setFocusable(false);
        jBtnAddRoom.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnAddRoom.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnAddRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddRoomActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnAddRoom);
        jBtnAddRoom.getAccessibleContext().setAccessibleName("jBtnAddRoom");

        jBtnDeleteRoom.setText(bundle.getString("DeleteRoomBtn")); // NOI18N
        jBtnDeleteRoom.setEnabled(false);
        jBtnDeleteRoom.setFocusable(false);
        jBtnDeleteRoom.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnDeleteRoom.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnDeleteRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeleteRoomActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnDeleteRoom);
        jBtnDeleteRoom.getAccessibleContext().setAccessibleName("jBtnDeleteRoom\n");

        jBtnAddGuest.setText(bundle.getString("AddGuestBtn")); // NOI18N
        jBtnAddGuest.setFocusable(false);
        jBtnAddGuest.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnAddGuest.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnAddGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddGuestActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnAddGuest);
        jBtnAddGuest.getAccessibleContext().setAccessibleName("jBtnAddGuest");

        jBtnDeleteGuest.setText(bundle.getString("DeleteGuestBtn")); // NOI18N
        jBtnDeleteGuest.setEnabled(false);
        jBtnDeleteGuest.setFocusable(false);
        jBtnDeleteGuest.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnDeleteGuest.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnDeleteGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeleteGuestActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnDeleteGuest);
        jBtnDeleteGuest.getAccessibleContext().setAccessibleName("jBtnDeleteGuest");

        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);
        jToolBar2.add(jSeparator19);

        jBtnFindEmptyRoom.setText(bundle.getString("FindEmptyRoomsBtn")); // NOI18N
        jBtnFindEmptyRoom.setFocusable(false);
        jBtnFindEmptyRoom.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnFindEmptyRoom.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnFindEmptyRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFindEmptyRoomActionPerformed(evt);
            }
        });
        jToolBar2.add(jBtnFindEmptyRoom);

        JBtnFindGuest.setText(bundle.getString("FindGuestReservationBtn")); // NOI18N
        JBtnFindGuest.setFocusable(false);
        JBtnFindGuest.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        JBtnFindGuest.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        JBtnFindGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnFindGuestActionPerformed(evt);
            }
        });
        jToolBar2.add(JBtnFindGuest);

        jBtnFindRoom.setText(bundle.getString("FindRoomReservationBtn")); // NOI18N
        jBtnFindRoom.setFocusable(false);
        jBtnFindRoom.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnFindRoom.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnFindRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFindRoomActionPerformed(evt);
            }
        });
        jToolBar2.add(jBtnFindRoom);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/transparency/misWeb2CLRtr.png"))); // NOI18N

        jMenu1.setText("Hotel");

        jMenuItemAbout.setText(bundle.getString("About")); // NOI18N
        jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemAbout);
        jMenu1.add(jSeparator1);

        jMenuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemExit.setText(bundle.getString("exit")); // NOI18N
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
        JOptionPane.showMessageDialog(this, texts.getString("about.authors") + "\n" 
                                                               + texts.getString("about.version") + "\n"
                                                               + texts.getString("about.edited") + "\n",
                                  texts.getString("About"),JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jMenuItemAboutActionPerformed

    private void jBtnAddGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddGuestActionPerformed
        showGuestFrame();
    }//GEN-LAST:event_jBtnAddGuestActionPerformed

    private void jBtnAddRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddRoomActionPerformed
        showRoomFrame();
    }//GEN-LAST:event_jBtnAddRoomActionPerformed

    private void jBtnAddResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddResActionPerformed
        showReservationFrame();
    }//GEN-LAST:event_jBtnAddResActionPerformed

    private void jBtnDeleteGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeleteGuestActionPerformed
        actionDeleteGuest();
    }//GEN-LAST:event_jBtnDeleteGuestActionPerformed

    private void jBtnDeleteRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeleteRoomActionPerformed
        actionDeleteRoom();
    }//GEN-LAST:event_jBtnDeleteRoomActionPerformed

    private void jTableGuestFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTableGuestFocusGained
       jBtnDeleteGuest.setEnabled(true);
    }//GEN-LAST:event_jTableGuestFocusGained

    private void jTableRoomFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTableRoomFocusGained
         jBtnDeleteRoom.setEnabled(true);
    }//GEN-LAST:event_jTableRoomFocusGained

    private void jTabbedPane2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane2StateChanged
       if (jTabbedPane2.getSelectedIndex() == 0) {
            jBtnDeleteRoom.setEnabled(false);
            jBtnDeleteGuest.setEnabled(false);
         }
    }//GEN-LAST:event_jTabbedPane2StateChanged

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jBtnFindEmptyRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFindEmptyRoomActionPerformed
       showEmptyRoomsOptionFrame();
    }//GEN-LAST:event_jBtnFindEmptyRoomActionPerformed

    private void jBtnDeleteResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeleteResActionPerformed
       actionCheckOut();
    }//GEN-LAST:event_jBtnDeleteResActionPerformed

    private void JBtnFindGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnFindGuestActionPerformed
        showFindGuestFrame();
    }//GEN-LAST:event_JBtnFindGuestActionPerformed

    private void jBtnFindRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFindRoomActionPerformed
       showFindRoomFrame();
    }//GEN-LAST:event_jBtnFindRoomActionPerformed

       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Napkin".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AppForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnFindGuest;
    private javax.swing.JButton jBtnAddGuest;
    private javax.swing.JButton jBtnAddRes;
    private javax.swing.JButton jBtnAddRoom;
    private javax.swing.JButton jBtnDeleteGuest;
    private javax.swing.JButton jBtnDeleteRes;
    private javax.swing.JButton jBtnDeleteRoom;
    private javax.swing.JButton jBtnFindEmptyRoom;
    private javax.swing.JButton jBtnFindRoom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JScrollPane jPaneGuest;
    private javax.swing.JScrollPane jPaneReservation;
    private javax.swing.JScrollPane jPaneRoom;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator19;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTableGuest;
    private javax.swing.JTable jTableReservation;
    private javax.swing.JTable jTableRoom;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    // End of variables declaration//GEN-END:variables
}
