CREATE TABLE rooms (
  roomID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  capacity INT,
  roomNumber VARCHAR(30)
);

CREATE TABLE guests (
  guestID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  phoneNumber VARCHAR(50),
  address VARCHAR(150),
  fullName VARCHAR(100)
);

CREATE TABLE reservations (
  reservationID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  startTime DATE,
  endTime DATE,
  roomID_FK BIGINT REFERENCES rooms(roomID) ON DELETE CASCADE,
  guestID_FK BIGINT REFERENCES guests(guestID) ON DELETE CASCADE,
  price DECIMAL
);